# config.py
# Este arquivo centraliza todas as variáveis de configuração do projeto.

# --- Caminhos e Nomes de Arquivos ---
PASTA_RAIZ_RELATORIOS = r'C:\Users\consultor.ale\Desktop\Mamede\Relatórios\MOVIMENTACOES'
PALAVRA_CHAVE_INVENTARIO = 'ppReport1inventario'
NOME_PLANILHA_ONLINE = "COMPROP_Dashboard_Data"
CAMINHO_CREDENCIAS_JSON = "credentials.json"
CAMINHO_EXCEL_LOCAL = r'C:\Users\consultor.ale\Desktop\Mamede\Relatórios\COMPROP_Dashboard_Data_Local.xlsx'
CAMINHO_LOGO = 'image_9b00e0.png'

# --- Dicionário de Mapeamento de Movimentação ---
movimentacao_map = {
    "1-VENDA DE MERCADORIAS - COOPERADO": "Saída", "18-COMPRA PARA INDUSTRIALIZACAO": "Entrada",
    "20-TRANSFERENCIA DE MERCADORIA SAIDA": "Saída", "21-TRANSFERENCIA DE MERCADORIA ENTRADA": "Entrada",
    "317-TRANSP. PARA ARMAZENAGEM": "Sem Movimentação", "319-VENDA DE MERCADORIAS - NAO COOPERADO": "Saída",
    "320-REMESSA DE MERC. ENT. FUT - NAO COOPERADO": "Saída", "328-ARMAZEM - REMESSA PARA DEPOSITO PRODUTOR": "Entrada",
    "329-ARMAZEM - RETORNO SIMBOLICO MERC. DEPOSITADA": "Saída", "331-ARMAZEM - RETORNO REMESSA MERCADORIA DEPOSITADA": "Saída",
    "338-RECLASSIFICACAO SAIDA": "Saída", "339-RECLASSIFICACAO ENTRADA": "Entrada",
    "34-VENDA DE PRESTACAO DE SERVICOS": "Sem Movimentação", "341-VENDA PARA ENT. FUTURA - NAO COOPERADO": "Saída",
    "342-ARMAZEM - RETORNO SIMBOLICO QUEBRA TECNICA": "Saída", "365-ARMAZEM - REMESSA SIMB. PARA DEPOSITO COM COBRANÇA": "Entrada",
    "368-IND - VENDA DE PRODUTO INDUSTRIALIZADO - COOPERADO": "Saída", "369-IND - VENDA DE PRODUTO INDUSTRIALIZADO - NAO COOPERADO": "Saída",
    "370-IND - VENDA PARA ENT. FUTURA - COOPERADO": "Sem Movimentação", "372-IND - REMESSA DE MERC. ENT. FUT - COOPERADO": "Saída",
    "375-ARMAZEM - OUTRAS ENT. - ESTORNO RET. SIMB. MERC. DEPOSITADA": "Saída", "398-ARMAZEM - COMPRA COM NF DE PRODUTOR (ESTOQUE DISPONIVEL)": "Entrada",
    "4-VENDA PARA ENT. FUTURA - COOPERADO": "Sem Movimentação", "5-REMESSA DE MERC. ENT. FUT - COOPERADO": "Saída",
    "53-SAIDA DE MERCADORIA EM BONIFICACAO": "Saída", "58-ARMAZEM - REMESSA MERC. CONTA ORDEM TERCEIROS": "Saída",
    "28-COMPRA DE MATERIAL USO E CONSUMO": "Entrada", "418-AQUISIÇÃO DE SERVIÇOS - CONSULTORIA EMPRESARIAL": "Entrada",
    "73-ENTRADA TRANSF. USO E CONSUMO": "Entrada", "390-IND - DEVOLUCAO DE VENDA NF PROPRIA": "Entrada",
    "2-DEVOLUCAO DE VENDA NF PROPRIA": "Entrada", "417-AQUISIÇÃO DE SERVIÇOS - MANUT. MAQU. E EQUIPAMENTOS": "Entrada",
    "441-AQUISIÇÃO DE SERVIÇOS - RET. FEDERAIS": "Entrada", "6-CONTA MOVIMENTO": "Sem Movimentação",
    "1-À VISTA": "Sem Movimentação", "8-À VISTA ENTRADAS": "Sem Movimentação", "3-PAGAMENTO A PRAZO": "Sem Movimentação",

}
