# rpa_module.py
# Este módulo contém exclusivamente a função que controla o mouse e o teclado
# para extrair os relatórios do software de gestão.

import pyautogui
import time
from datetime import date

def executar_rpa_extracao(pasta_destino, data_inicial_str, data_final_str):
    """Executa a automação com PyAutoGUI para extrair os relatórios em PDF."""
    print("--- ETAPA 0: Iniciando Automação (RPA) para Extrair os PDFs ---")
    print(f"  > Período de extração: de {data_inicial_str} a {data_final_str}")
    for i in range(5, 0, -1):
        print(f"Iniciando em {i} segundos...")
        time.sleep(1)
    print("Iniciando automação!")
    
    try:
        pyautogui.PAUSE = 1.0
        
        pyautogui.click(x=1395, y=15)
        pyautogui.doubleClick(x=34, y=432) 
        time.sleep(3)
        pyautogui.click(x=566, y=620) 
        pyautogui.write('Unique@nail2025', interval=0.1)
        pyautogui.press('enter')
        time.sleep(7)
        pyautogui.click(x=740, y=610) 
        time.sleep(6)
        pyautogui.click(x=921, y=34) 
        pyautogui.click(x=1000, y=133) 
        pyautogui.click(x=1164, y=133) 
        pyautogui.click(x=962, y=186)
        time.sleep(4)
        pyautogui.click(x=558, y=287)
        pyautogui.write(data_inicial_str, interval=0.2)
        pyautogui.click(x=784, y=287)
        pyautogui.write(data_final_str, interval=0.2)
        pyautogui.press('enter')
        pyautogui.click(x=534, y=101)
        time.sleep(6)
        pyautogui.click(x=559, y=35)
        time.sleep(2)
        pyautogui.click(x=675, y=555)
        pyautogui.write('Entrada')
        pyautogui.press('enter')
        time.sleep(2)
        pyautogui.click(x=809, y=468)
        time.sleep(5)
        pyautogui.click(x=1395, y=15)
        time.sleep(1)
        pyautogui.click(x=1488, y=6)
        time.sleep(1)
        pyautogui.click(x=1062, y=69)
        time.sleep(1)
        pyautogui.click(x=942, y=32) 
        pyautogui.click(x=1067, y=137) 
        pyautogui.click(x=1182, y=157) 
        pyautogui.click(x=1008, y=163)
        time.sleep(4)
        pyautogui.click(x=558, y=287)
        pyautogui.write(data_inicial_str, interval=0.2)
        pyautogui.click(x=784, y=287)
        pyautogui.write(data_final_str, interval=0.2)
        pyautogui.press('enter')
        pyautogui.click(x=534, y=101)
        time.sleep(6)
        pyautogui.click(x=559, y=35)
        time.sleep(2)
        pyautogui.click(x=675, y=555)
        pyautogui.write('Saidas')
        pyautogui.press('enter')
        time.sleep(2)
        pyautogui.click(x=809, y=468)
        time.sleep(30)
        pyautogui.click(x=1395, y=15)
        time.sleep(1)
        pyautogui.click(x=1488, y=6)
        time.sleep(1)
        pyautogui.click(x=1062, y=69)
        time.sleep(1)
        pyautogui.click(x=949, y=34) 
        pyautogui.click(x=1061, y=111) 
        pyautogui.click(x=1177, y=110)
        time.sleep(3)
        pyautogui.write(data_final_str, interval=0.2)
        pyautogui.click(x=589, y=289)
        pyautogui.write(data_final_str, interval=0.2)
        pyautogui.press('enter')
        pyautogui.click(x=559, y=154)
        time.sleep(1)
        pyautogui.click(x=928, y=542)
        time.sleep(20)
        pyautogui.click(x=562, y=34)
        time.sleep(2)
        pyautogui.click(x=713, y=559)
        pyautogui.write('inventario')
        pyautogui.press('enter')
        time.sleep(2)
        pyautogui.click(x=805, y=467)
        time.sleep(20)
        pyautogui.click(x=354, y=21)
        print("--- ETAPA 0: Automação Concluída com Sucesso! ---\n")
        return True

    except Exception as e:
        pyautogui.alert(f"Ocorreu um erro durante a automação RPA: {e}")
        return False